# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

addons:
  apt:
    packages:
      - python-numpy
      - python-scipy

cache:
  - packages

before_install:
  - pip install --user --quiet --upgrade pip
  - travis_wait pip install --user --quiet -U scikit-learn
