# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  - packages
  - pip
before_install:
  - pip install --user --quiet --upgrade pip
  - travis_wait pip install --user --quiet numpy
  - travis_wait pip install --user --quiet scipy
  - travis_wait pip install --user --quiet -U scikit-learn
